# Generated by Django 5.0.3 on 2024-04-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sock_alter_wear_options_alter_wear_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='socks',
            field=models.ManyToManyField(to='main_app.sock'),
        ),
    ]
